AS.PERGOD.REDUCE.MEMORY.LAG.TO.ZERO.AS.L2-CACHE.SHOULD.BE.HANDELED.BY.MAIN.BOARD.AND.NOT.BY""""___happy__face___uifi___sadface__no?y.
  
use.common.hardware.DRIVERS.TIED.TO.1.DLL2.DLL3.DLL.
  
USE.REGEDIT.TO.ENDUCE.THOSE.FILES.BY.COMMONgod.
  
Copyright Jesper Hessel.
